drop table if exists mta_users;
create table mta_users (
    id bigint generated by default as identity,
    username varchar(255),
    password varchar(255),
    display_name varchar(255),
    registration_date date,
    locked boolean not null,
    primary key (id)
);

drop table if exists user_roles;
create table user_roles (
    user_id bigint not null,
    user_role varchar(255)
);

drop table if exists tests;
create table tests (
    id bigint generated by default as identity,
    creation_date date,
    difficulty integer not null,
    duration integer not null,
    name varchar(255),
    subject varchar(255),
    primary key (id)
);

drop table if exists questions;
create table questions (
    id bigint generated by default as identity,
    multiple boolean not null,
    text varchar(255),
    test_id bigint,
    primary key (id),
    foreign key (test_id) references tests (id)
        on delete cascade
);

drop table if exists options;
create table options (
    id bigint generated by default as identity,
    correct boolean not null,
    text varchar(255),
    question_id bigint,
    primary key (id),
    foreign key (question_id) references questions (id)
        on delete cascade
);

drop table if exists attempts;
create table attempts (
    id bigint generated by default as identity,
    score varchar(255),
    test_id bigint,
    user_id bigint,
    primary key (id)
);
